// learn-react/08/todo_useEffect/src/components/TodoListItem.tsx
import React, { useId } from "react";

export default React.memo(function TodoListItem({
  todo,
  removeTodo,
  toggleTodo,
}: {
  todo: Todo;
  removeTodo: (id: number) => void;
  toggleTodo: (id: number) => void;
}) {
  console.log("todoListItem rendering");
  const uuid = useId();
  return (
    <li className="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors">
      <div className="flex items-center">
        <input
          id={uuid}
          type="checkbox"
          className="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
          checked={todo.completed}
          onChange={() => toggleTodo(todo.id)}
        />
        <label htmlFor={uuid} className={`${todo.completed && "line-through"}`}>
          {todo.text}
        </label>
      </div>
      <button
        className="text-red-500 hover:text-red-700 ml-4"
        onClick={() => removeTodo(todo.id)}
      >
        Delete
      </button>
    </li>
  );
});

// learn-vue/20250113/todoList/todo-options/src/components/TodoListItem.vue
<script>
export default {
  props: {
    todo: {
      type: Object,
    },
  },
  emits: ["toggle-todo", "delete-todo"],
  beforeCreate() {
    console.log("beforeCreate");
  },
  updated() {
    console.log("updated");
  },
};
</script>
<template>
  <li
    className="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors"
  >
    <div :class="`flex items-center ${todo.done && 'line-through'}`">
      <input
        type="checkbox"
        className="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
        :checked="todo.done"
        @change="$emit('toggle-todo', todo.id)"
      />
      <span>{{ todo.text }}</span>
    </div>
    <button
      className="text-red-500 hover:text-red-700 ml-4"
      @click="$emit('delete-todo', todo.id)"
    >
      Delete
    </button>
  </li>
</template>
<style></style>
