// learn-vue/20240113/todoList/todo-options/src/components/Todo.vue
<script>
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";

export default {
  components: {
    TodoHeader,
    TodoEditor,
    TodoList,
  },
  data() {
    return {};
  },
};
</script>
<template>
  <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style></style>

// learn-react/07/todo/src/components/Todo.tsx
import TodoEditor from './TodoEditor';
import TodoHeader from './TodoHeader';
import TodoList from './TodoList';

export default function Todo() {
  return (
    <div className='max-w-md mx-auto shadow-lg rounded-lg overflow-hidden'>
      <TodoHeader />
      <TodoEditor />
      <TodoList />
    </div>
  );
}
