// learn-vue/20250113/todoList/todo-options/src/components/TodoList.vue
<script>
import TodoListItem from "./TodoListItem.vue";

export default {
  components: {
    TodoListItem,
  },
  props: {
    todos: {
      type: Array,
      default: () => [],
    },
  },
  methods: {
    toggleTodo(id) {
      this.$emit("toggle-todo", id);
    },
    deleteTodo(id) {
      this.$emit("delete-todo", id);
    },
  },
};
</script>
<template>
  <ul className="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
      @toggle-todo="toggleTodo"
      @delete-todo="deleteTodo"
    />
  </ul>
</template>
<style></style>

// learn-react/07/todo/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  delTodo,
  checkedTodo,
}: {
  todos: todoType[];
  delTodo: (id: number) => void;
  checkedTodo: (id: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo) => (
        <TodoListItem
          id={todo.id}
          content={todo.content}
          completed={todo.completed}
          key={todo.id}
          delTodo={delTodo}
          checkedTodo={checkedTodo}
        />
      ))}
    </ul>
  );
}
