// learn-react/07/todo/src/components/TodoEditor.tsx
export default function TodoEditor() {
  return (
    <div className='flex p-4'>
      <input
        type='text'
        placeholder='Enter a new todo'
        className='flex-grow p-2 border rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500'
      />
      <button className='bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors'>
        Add Todo
      </button>
    </div>
  );
}

// learn-vue/20240113/todoList/todo-options/src/components/TodoEditor.vue
<script>
export default {
  data() {
    return {};
  },
};
</script>
<template>
  <div className="flex p-4">
    <input
      type="text"
      placeholder="Enter a new todo"
      className="flex-grow p-2 border rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500"
    />
    <button
      className="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors"
    >
      Add Todo
    </button>
  </div>
</template>
<style></style>
